alias: Mail Box
description: ""
trigger:
  - platform: state
    entity_id: binary_sensor.mailbox
    to: "on"
condition: []
action:
  - service: notify.notify
    data:
      message: You have mail!
  - service: mqtt.publish
    data:
      topic: homeassistant/binary_sensor/mailbox/state
      payload: empty
      retain: true