- id: "1693702614043"
  alias: Mailbox Guard Motion
  description: ""
  trigger:
    - platform: state
      entity_id: input_boolean.mailbox_guard_motion
      to: "on"
  condition: []
  action:
    - service: notify.notify
      data:
        message: You've Got Mail!
    - service: input_number.set_value
      data:
        entity_id: input_number.mailbox_guard_count
        value: "{{ (states.input_number.mailbox_guard_count.state | int) + 1 }}"
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.mailbox_guard_motion
  mode: single
- id: "1693703621871"
  alias: Mailbox Guard Low Battery
  description: ""
  trigger:
    - platform: state
      entity_id: input_boolean.mailbox_guard_low_battery
      to: "on"
  condition: []
  action:
    - service: notify.notify
      data:
        message: Mailbox Guard Low Battery!
  mode: single
